$ANSIBLE_VAULT;1.1;AES256
65353239386234303665333039353330366462643135653835353336303934323133323933356437
3063633666356538363033623865313563633436646138310a383963333732636239366135633365
66326439653361363230643732383733373139373132643830343331333932623530313934636364
3630323330666338620a353839653566363437663837373466333865653664653235633437663764
37633633376338383932653331626632396434326632383736633234386236626565396631383066
31393834373065356138326134623861323834623239353632646661383433396239393430653034
35663463356234613831366331373330323438633436656366356539303661393339343263343933
31373135666532336266313066303039616564643939306164373337393036396266343136613030
33353865346433663037663432663061353564346236633264353531326664666232633337363936
31633935323838323733306538323232343735336235373066306365323432333234396335616339
39333239663738343163376436346635326462666437346264346530663038613166313036343531
34383564303239643866613539383738623761313061353963626430343666333339376665346437
62336437363333323665623636326537373632663339626564646133376337336637666366656538
32616334396434643938333832326233626632346435336335396565613733646631316264356662
61326261393236333738663938323963616236323532376633623332636635666265373434633365
63383634323561306430306436653033643562623532636366323739396539303434383735633331
62633564616538316564636363373138646361333531633564313165376166306633
